### ISSUE TITLE
summary message auto kicks you if too long (host only)

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#28]
The summary message is set to send to everyone, and innersloth's anticheat boots you whenever it is longer than 100 characters. Perhaps make it a client only message like "player joined the lobby"?

I made a personal compiled version of 1.1.30 myself and changed this in GameStartPatch.cs. This change seemed to fix the issue for me:

before:
PlayerControl.LocalPlayer.RpcSendChat(StartPatch.s);

after:
DestroyableSingleton<HudManager>.Instance.Chat.AddChat(PlayerControl.LocalPlayer, StartPatch.s);

**Comment by Night-GUA** [comment]
i change it now, it in the commit

**Comment by Night-GUA** [comment]
discord server link will change, please wait

**Comment by Night-GUA** [comment]
[New Discord Server Link](https://discord.gg/42tyx9FyD7)

**Comment by Night-GUA** [comment]
because we have a installer
I will update the installer to YuEzTools version, please wait
