### ISSUE TITLE
Illegal Sabotages ban the host instead of the person who executed the sabotage (skeld only)

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#29]
When a sabotage hack command is used, the host gets banned as if their name was "SkeldShip(Clone)". This only happens on the skeld map.

All sabotages except lights are automatically canceled for the following maps:
- Mira HQ
- Polus
- Airship
- Fungle (lights sabotage does not exist on this map)

**Comment by Night-GUA** [comment]
But in my tesst, no this problem
Please give me log

**Comment by Night-GUA** [comment]
Are you in the hide & seek mode?

**Comment by Night-GUA** [comment]
I can see the PlayerControl read myself, but I can't find the bug by what

**Comment by Night-GUA** [comment]
I see, it's amazing

**Comment by Night-GUA** [comment]
because it is bug

**Comment by Sand-and-Beans** [comment]
> because it is bug

pc老毛病

**Comment by Night-GUA** [comment]
> > because it is bug因为它是bug
> 
> old bug 老bug

但是嗷，我觉得他不应该报这个问题，我去源码看看

**Comment by Sand-and-Beans** [comment]
> > > because it is bug因为它是bug
> > 
> > 
> > old bug 老bug
> 
> 但是嗷，我觉得他不应该报这个问题，我去源码看看

pc获取的一直是飞船名称，就是之前说的那个

**Comment by Night-GUA** [comment]
很难绷

**Comment by Night-GUA** [comment]
it's amongus's bug, i will close the issue, thanks your issue

**Comment by Sand-and-Beans** [comment]
> When a sabotage hack command is used, the host gets banned as if their name was "SkeldShip(Clone)". This only happens on the skeld map.
> 
> All sabotages except lights are automatically canceled for the following maps:
> 
> * Mira HQ
> * Polus
> * Airship
> * Fungle (lights sabotage does not exist on this map)

The mistake was found and it will be fixed in the next version I guess. Thx =D

**Comment by redphantom1000** [comment]
@Sand-and-Beans i know. I'm in the EZtools discord so i can get github updates there
