### ISSUE TITLE
Missing english translations

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#30]
There are missing translations in several areas of English.yaml (and probably Chinese traditional/Japanese too).

This file contains fixed translations based on the Chinese simplified YAML file. You may need to manually verify most of the lines as several of them were translated using Google Translate prompts. 
_The file extension was changed to TXT because github does not support YAML uploads_

[English modified.yaml.txt](https://github.com/user-attachments/files/16487586/English.modified.yaml.txt)

lines 46 and 47 were not translated

**Comment by Night-GUA** [comment]
may you can give me pr

**Comment by Night-GUA** [comment]
thanks, i will check

**Comment by Night-GUA** [comment]
translations is true, I will merge in my project, thank you to give our translations!

**Comment by Night-GUA** [comment]
You're welcome,too
