### ISSUE TITLE
[suggestion] kick/ban as host in meetings

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#32]
This is more of a suggestion instead of a bug report. Hosts who have mods like TOHE have this functionality in meetings, but only votekicking is supported in YuEzTools based on my last testing today. Is this only possible with the +25 mode enabled on the lobby or can it be done without it?

![image](https://github.com/user-attachments/assets/e2bdb6c3-ca54-448a-be8d-57b5e8188142)

**Comment by Night-GUA** [comment]
After discussions between our developers and Chinese players, we will not be adding this feature

**Comment by Night-GUA** [comment]
Because some host are bad host

**Comment by Pietrodjaowjao** [comment]
> Because some host are bad host

this makes no sense

**Comment by Pietrodjaowjao** [comment]
the host can ban in lobby then, if the host is bad ppl should just leave

**Comment by Night-GUA** [comment]
Ok, we'll discuss it again
