### ISSUE TITLE
Installer files for first time BepInEx mod users

### ISSUE THREAD

**Issue by redphantom1000** [Team-YuTeam/YuEzTools#34]
Currently missing from all updates after 1.1.1.20. Are you going to add those on release 1.3.0.0? You said you would do that on another issue I reported

Or can we just use the windows version of this and put the DLL in the `BepinEx/plugins` folder?
https://github.com/BepInEx/BepInEx/releases

**Comment by Night-GUA** [comment]
may you should
https://github.com/Night-GUA/YuET-Installer/releases

**Comment by Night-GUA** [comment]
and you can download the bepinex from here
https://builds.bepinex.dev/projects/bepinex_be/688/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.688%2B4901521.zip

**Comment by Night-GUA** [comment]
It's my question, may main has some bug

**Comment by Night-GUA** [comment]
I fix it now, I will release a new version soon
