### ISSUE TITLE
Translation fixes #3

### ISSUE THREAD

**Issue by red88phantom** [Team-YuTeam/YuEzTools#38]
Added the following translations to 
# [English.yaml.txt](https://github.com/user-attachments/files/16534035/English.yaml.txt):

- BlackList
- VerShow.Visit
- UsingVersion
- iPhone
- Android
- Platforms.Unknown

If you want to know how i'm finding the missing matches quickly, I am using Notepad++ with the ComparePlus plugin

**Comment by Night-GUA** [comment]
That's so cool
I hope you give me Pull Request
Proficiency in Git and PR will make your name among our project contributors and will allow you to quickly find the missing parts
