### ISSUE TITLE
[Question] quit button?

### ISSUE THREAD

**Issue by VixenSugo** [Team-YuTeam/YuEzTools#42]
where is quit button in v1.3.5.1 ?
Why don't you optimize the mod for both available languages?
Half English, half Chinese, not very interesting

**Comment by Night-GUA** [comment]
I will  fixed, thanks

**Comment by Night-GUA** [comment]
the button bug will fix on next version, and the installer
you can see [YuET Installer](github.com/Night-GUA/YuET-Installer)
