### ISSUE TITLE
[Bug] im kicked by AU anti cheat when im host

### ISSUE THREAD

**Issue by raddanzin** [Team-YuTeam/YuEzTools#52]
the update is great, but i can't play as host in this way. i create the room, a player join and im kicked in instant...

**Comment by Night-GUA** [comment]
Probabilistic issues, which cannot be solved, please provide logs

**Comment by redphantom1000** [comment]
@raddanzin whenever this happens use F1 on your keyboard to export logs. then post them here

**Comment by Endarkpb** [comment]
[YuET-v1.3.6.2-2024-08-19_13.48.55.log](https://github.com/user-attachments/files/16657061/YuET-v1.3.6.2-2024-08-19_13.48.55.log)

**Comment by Night-GUA** [comment]
fixed
